{{- if .Values.runner.pat }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-runner.patSecretName" . }}
  labels:
    {{- include "edge-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  pat: {{ .Values.runner.pat | quote }}
{{- end }}
