apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-runner.fullname" . }}
  labels:
    {{- include "edge-runner.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "edge-runner.selectorLabels" . | nindent 4 }}
